spring.application.name=journal-backend
# DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/journal
spring.datasource.username=journal
spring.datasource.password=password

# Auto create/update table base on Java Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Virtual Threads
spring.threads.virtual.enabled=true


# MinIO
minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=trading-journal

# Logging
logging.config=classpath:logback-spring.xml

# Encrypt service
app.security.encrypt-key=1234567890123456

# App Environment
app.env=development

# Jackson config
spring.jackson.generator.write-bigdecimal-as-plain=true

# Hibernate config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect